Repository njfamirm/blog, pull requests merged in 2023-09, with the labels that each got.

#24 feat: update prayer and add kalameh font
  assets/font/kalameh/kalameh-100.woff
  assets/font/kalameh/kalameh-100.woff2
  assets/font/kalameh/kalameh-400.woff
  assets/font/kalameh/kalameh-400.woff2
  assets/font/kalameh/kalameh-700.woff
  assets/font/kalameh/kalameh-700.woff2
  assets/font/kalameh/kalameh-900.woff
  assets/font/kalameh/kalameh-900.woff2
  img/prayer/ale-yasin/cover.jpg
  site/_css/font.css
  site/_css/kalameh-font.css
  site/_css/prayer.css
  site/_css/vazirmatn-font.css
  site/_includes/prayer-list.njk
  site/_layouts/prayer.njk
  site/_style.njk
  site/fa/prayer/ale-yasin.md
  tailwind.config.js
Labels: new-feature

#31 feat: rewrite blog
  .github/dependabot.yml
  .github/workflows/publish-container.yml
  assets/img/authors/njfamirm.jpg
  assets/img/blog/git-separate/big-pr-screenshot.jpg
  assets/img/blog/git-separate/cover.jpg
  assets/img/blog/git-separate/git-commit-screenshot.jpg
  assets/img/blog/git-separate/git-rebase-branch-screenshot.jpg
  assets/img/blog/git-separate/git-rebase.jpg
  assets/img/blog/git-separate/smaller-pr-screenshot.jpg
  assets/img/blog/git-separate/trunk-based-deployment.jpg
  assets/img/blog/self-hosting-decap-cms/cover.jpg
  assets/img/blog/self-hosting-decap-cms/create-oauth-screenshot.jpg
  assets/img/blog/self-hosting-decap-cms/oauth-setting-screenshot.jpg
  assets/img/meta/icon-512-maskable.png
  assets/img/meta/icon-512.png
  assets/img/meta/social.jpg
  assets/img/meta/social.png
  assets/img/prayer/ale-yasin/cover.jpg
  eleventy.config.cjs
  package.json
  site/_css/base.css
  site/_css/blog-post.css
  site/_css/font.css
  site/_css/main.css
  site/_css/post.css
  site/_css/prayer.css
  site/_data/nav.json
  site/_feed.njk
  site/_includes/blog-post-list.njk
  site/_includes/header.njk
  site/_includes/meta.njk
  site/_includes/navigation-drawer.njk
  site/_includes/post-list.njk
  site/_includes/prayer-list.njk
  site/_includes/prayer-post-list.njk
  site/_includes/structured-data/blog.njk
  site/_includes/structured-data/breadcrumb.njk
  site/_js/header.ts
  site/_layouts/base.njk
  site/_layouts/blog-post.njk
  site/_layouts/post.njk
  site/_layouts/prayer.njk
  site/_style.njk
  site/en/blog.njk
  site/en/blog/blog.json
  site/en/blog/git-separate.md
  site/en/blog/self-hosting-decap-cms.md
  site/en/home.njk
  site/en/post.njk
  site/en/post/post.json
  site/en/reading.njk
  site/fa/fa.json
  site/fa/prayer.njk
  site/fa/prayer/ale-yasin.md
  site/fa/prayer/prayer.json
  tailwind.config.js
  yarn.lock
Labels: enhancement

#34 feat(blog): strapi custom api post
  .vscode/settings.json
  assets/img/blog/strapi-custom-api/api-permission.jpg
  assets/img/blog/strapi-custom-api/api-result.jpg
  assets/img/blog/strapi-custom-api/content-type.jpg
  assets/img/blog/strapi-custom-api/cover.jpg
  cloud/env/njfamirm-ws-beta.env
  site/_css/blog-post.css
  site/_layouts/blog-post.njk
  site/en/blog/strapi-custom-api.md
  site/en/reading.njk
Labels: documentation

#37 feat: add release system
  .github/workflows/github-release.yml
  .versionrc.json
  package.json
  yarn.lock
Labels: new-feature

#48 feat: load reading list from strapi
  .github/workflows/build.yaml
  .github/workflows/publish-container.yml
  .gitignore
  cloud/Dockerfile
  eleventy.config.cjs
  filter/date.js
  filter/keyword.js
  filter/postcss.js
  filter/url.js
  package.json
  site/_data/readingList.js
  site/en/reading.njk
  site/en/reading/_feed.njk
  site/en/reading/conventional-changelog.md
  site/en/reading/conversational-commit.md
  site/en/reading/dependabot-group-update.md
  site/en/reading/feed-best-practice.md
  site/en/reading/http-203.md
  site/en/reading/json-schema.md
  site/en/reading/reading.json
  site/en/reading/semver.md
  site/en/reading/surma-ws.md
  transform/esbuild.js
  transform/minify-html.js
  yarn.lock
Labels: new-feature

#36 docs(blog): improve strapi-custom-api to fix some best practices
  site/en/blog/strapi-custom-api.md
Labels: documentation, enhancement
